// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBTWXhus9VTkAXwh0kuxb5LPq3xQUlgJ_A',
    appId: '1:344506256262:web:a725a4f0f0ddab4fbbba07',
    messagingSenderId: '344506256262',
    projectId: 'flutter-test-78f5a',
    authDomain: 'flutter-test-78f5a.firebaseapp.com',
    storageBucket: 'flutter-test-78f5a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm_fEsRjn9TwcM-hsdIxROB7SADeUG9Qw',
    appId: '1:344506256262:android:a26c7aa8932fe7f0bbba07',
    messagingSenderId: '344506256262',
    projectId: 'flutter-test-78f5a',
    storageBucket: 'flutter-test-78f5a.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBTWXhus9VTkAXwh0kuxb5LPq3xQUlgJ_A',
    appId: '1:344506256262:web:d29a931ecd9039b0bbba07',
    messagingSenderId: '344506256262',
    projectId: 'flutter-test-78f5a',
    authDomain: 'flutter-test-78f5a.firebaseapp.com',
    storageBucket: 'flutter-test-78f5a.appspot.com',
  );
}
